[versions]
hikari = "3.4.5"
guava = "30.0-jre"
gson = "2.8.6"
yaml = "2.0"
common-lang3 = "3.11"
common-io = "2.7"
annotations = "19.0.0"
lombok = "1.18.24"
persistence-api = "2.2"
asm = "9.6"
packetevents = "2.2.1"
bukkit-api = "1.16.5-R0.1-SNAPSHOT"

# Adventure
adventure = "4.16.0"
adventure-platform = "4.3.2"

# testing
junit = "5.9.0"
mockito = "4.11.0"

[libraries]
spigot = { module = "org.spigotmc:spigot-api", version.ref = "bukkit-api" }
paper = { module = "com.destroystokyo.paper:paper-api", version.ref = "bukkit-api" }

hikari-cp = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
yaml = { module = "org.yaml:snakeyaml", version.ref = "yaml" }
common-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "common-lang3" }
common-io = { module = "commons-io:commons-io", version.ref = "common-io" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
javax-persistence-api = { module = "javax.persistence:javax.persistence-api", version.ref = "persistence-api" }

# testing
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }

# PacketEvents
packetevents-api = { module = "com.github.retrooper.packetevents:api", version.ref = "packetevents" }
packetevents-spigot = { module = "com.github.retrooper.packetevents:spigot", version.ref = "packetevents" }

# ASM
asm-core = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }

# Adventure
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-text-serializer-gson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "adventure" }
adventure-text-serializer-legacy = { module = "net.kyori:adventure-text-serializer-legacy", version.ref = "adventure" }
adventure-nbt = { module = "net.kyori:adventure-nbt", version.ref = "adventure" }
adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
adventure-text-serializer-gson-legacy-impl = { module = "net.kyori:adventure-text-serializer-gson-legacy-impl", version.ref = "adventure" }
adventure-text-serializer-plain = { module = "net.kyori:adventure-text-serializer-plain", version.ref = "adventure" }

adventure-platform-bukkit = { module = "net.kyori:adventure-platform-bukkit", version.ref = "adventure-platform" }
adventure-platform-text-serializer-bungee = { module = "net.kyori:adventure-text-serializer-bungeecord", version.ref = "adventure-platform" }

[bundles]
asm = ["asm-core", "asm-commons"]
adventure = ["adventure-api", "adventure-text-serializer-gson", "adventure-text-serializer-legacy", "adventure-nbt", "adventure-text-minimessage", "adventure-text-serializer-gson-legacy-impl", "adventure-text-serializer-plain"]

[plugins]