[versions]
jackson = "2.11.2"
hikari = "3.4.5"
guava = "30.0-jre"
gson = "2.8.6"
yaml = "1.26"
common-lang3 = "3.11"
common-io = "2.7"
annotations = "19.0.0"
lombok = "1.18.24"
persistence-api = "2.2"
junit = "5.8.1"
asm = "9.3"

# Adventure
adventure = "4.10.1"
adventure-platform = "4.1.0"

[libraries]
# Jackson
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
hikari-cp = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
yaml = { module = "org.yaml:snakeyaml", version.ref = "yaml" }
common-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "common-lang3" }
common-io = { module = "commons-io:commons-io", version.ref = "common-io" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
javax-persistence-api = { module = "javax.persistence:javax.persistence-api", version.ref = "persistence-api" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

# ASM
asm-core = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }

# Adventure
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-text-serializer-gson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "adventure" }
adventure-text-serializer-legacy = { module = "net.kyori:adventure-text-serializer-legacy", version.ref = "adventure" }
adventure-nbt = { module = "net.kyori:adventure-nbt", version.ref = "adventure" }
adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
adventure-text-serializer-gson-legacy-impl = { module = "net.kyori:adventure-text-serializer-gson-legacy-impl", version.ref = "adventure" }
adventure-text-serializer-plain = { module = "net.kyori:adventure-text-serializer-plain", version.ref = "adventure" }

adventure-platform-bukkit = { module = "net.kyori:adventure-platform-bukkit", version.ref = "adventure-platform" }

[bundles]
jackson = ["jackson-core", "jackson-databind", "jackson-annotations", "jackson-datatype-jsr310"]
asm = ["asm-core", "asm-commons"]
adventure = ["adventure-api", "adventure-text-serializer-gson", "adventure-text-serializer-legacy", "adventure-nbt", "adventure-text-minimessage", "adventure-text-serializer-gson-legacy-impl", "adventure-text-serializer-plain"]

[plugins]